[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
proc-macro = true
name = "test_stand_derive"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1"
quote = "1"
devise = "0.3"
